# .drone.yml: build image and push to DockerHub

kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: johntellsall/gg-cache
    tags: latest
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    when:
      branch: master