version: '3.6'
services:

  caching-service:
    build:
      context: .
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis
    ports:
      - "5000:5000"
    volumes:
      - ./:/code/

  redis:
    image: redis:3.2-alpine
